# Generated by Django 6.0.8 on 2026-09-07 08:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], max_length=16)),
                ('content', models.TextField(blank=True)),
                ('tool_name', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentCitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=240)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('version', models.CharField(blank=True, max_length=40)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('excerpt', models.TextField(blank=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citations', to='agentkit.agentmessage')),
            ],
        ),
        migrations.CreateModel(
            name='AgentSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New conversation', max_length=160)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_activity_at',),
            },
        ),
        migrations.AddField(
            model_name='agentmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agentkit.agentsession'),
        ),
        migrations.CreateModel(
            name='AgentAuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('target_type', models.CharField(blank=True, max_length=80)),
                ('target_id', models.CharField(blank=True, max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agentkit.agentsession')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AgentActionProposal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('payload', models.JSONField(default=dict)),
                ('argument_fingerprint', models.CharField(max_length=64)),
                ('target_key', models.CharField(blank=True, max_length=200)),
                ('target_version', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('conflict', 'Conflict'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_action_proposals', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_proposals', to='agentkit.agentsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='agentsession',
            index=models.Index(fields=['owner', 'last_activity_at'], name='agent_session_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='agentmessage',
            index=models.Index(fields=['session', 'created_at'], name='agent_message_session_idx'),
        ),
        migrations.AddIndex(
            model_name='agentactionproposal',
            index=models.Index(fields=['owner', 'status', 'expires_at'], name='agent_proposal_owner_idx'),
        ),
    ]
